version: '3'

services:
   middleware:
    container_name: "mina_${MODE}"
    image: "mina_poc:1.0"
    build:
         context: .
         dockerfile: Dockerfile.${MODE}
    networks:
      - mina-ntk
   nginx:
    image: nginx:1.25.3-alpine3.18
    # build:
    #      context: ${PWD}/nginx/
    #      dockerfile: Dockerfile
    ports:
       - '80:80'
       - '443:443'   
    networks:
      - mina-ntk
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ${PWD}/nginx/mime.types:/etc/nginx/conf/mime.types:ro 
      - /etc/letsencrypt/live/zkapps.it/fullchain.pem:/etc/letsencrypt/live/zkapps.it/fullchain.pem:ro
      - /etc/letsencrypt/live/zkapps.it/privkey.pem:/etc/letsencrypt/live/zkapps.it/privkey.pem:ro    
      - ${PWD}/nginx/.htpasswd:/etc/nginx/conf/.htpasswd:ro            
networks:
  mina-ntk:
    driver: bridge